/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CloseIcon: typeof import('./src/components/MenuBar/CloseIcon.vue')['default']
    FileView: typeof import('./src/components/view/FileView/index.vue')['default']
    FuncButton: typeof import('./src/components/ToolTabBar/FuncButton.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar/index.vue')['default']
    SessionView: typeof import('./src/components/view/SessionView/index.vue')['default']
    SettingView: typeof import('./src/components/view/settingView/index.vue')['default']
    ShellTabBar: typeof import('./src/components/ShellTabBar/index.vue')['default']
    ShellView: typeof import('./src/components/ShellView/index.vue')['default']
    TabBar: typeof import('./src/components/TabBar/index.vue')['default']
    TinyAutocomplete: typeof import('@opentiny/vue-autocomplete')['default']
    TinyBaseSelect: typeof import('@opentiny/vue-base-select')['default']
    TinyButton: typeof import('@opentiny/vue-button')['default']
    TinyCheckbox: typeof import('@opentiny/vue-checkbox')['default']
    TinyCheckboxGroup: typeof import('@opentiny/vue-checkbox-group')['default']
    TinyDatePicker: typeof import('@opentiny/vue-date-picker')['default']
    TinyDialogBox: typeof import('@opentiny/vue-dialog-box')['default']
    TinyDropTimes: typeof import('@opentiny/vue-drop-times')['default']
    TinyForm: typeof import('@opentiny/vue-form')['default']
    TinyFormItem: typeof import('@opentiny/vue-form-item')['default']
    TinyInput: typeof import('@opentiny/vue-input')['default']
    TinyIpAddress: typeof import('@opentiny/vue-ip-address')['default']
    TinyNumeric: typeof import('@opentiny/vue-numeric')['default']
    TinyOption: typeof import('@opentiny/vue-option')['default']
    TinyRadio: typeof import('@opentiny/vue-radio')['default']
    TinyRadioGroup: typeof import('@opentiny/vue-radio-group')['default']
    TinySelect: typeof import('@opentiny/vue-select')['default']
    TinyTabItem: typeof import('@opentiny/vue-tab-item')['default']
    TinyTabs: typeof import('@opentiny/vue-tabs')['default']
    TinyTooltip: typeof import('@opentiny/vue-tooltip')['default']
    TinyTreeMenu: typeof import('@opentiny/vue-tree-menu')['default']
    ToolTabBar: typeof import('./src/components/ToolTabBar/index.vue')['default']
  }
}
