/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CloseIcon: typeof import('./src/components/MenuBar/CloseIcon.vue')['default']
    FileView: typeof import('./src/components/view/FileView/index.vue')['default']
    FuncButton: typeof import('./src/components/ToolTabBar/FuncButton.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar/index.vue')['default']
    SessionView: typeof import('./src/components/view/SessionView/index.vue')['default']
    SettingView: typeof import('./src/components/view/settingView/index.vue')['default']
    ShellTabBar: typeof import('./src/components/ShellTabBar/index.vue')['default']
    ShellView: typeof import('./src/components/ShellView/index.vue')['default']
    TabBar: typeof import('./src/components/TabBar/index.vue')['default']
    TinyButton: typeof import('@opentiny/vue-button')['default']
    TinyTabItem: typeof import('@opentiny/vue-tab-item')['default']
    TinyTabs: typeof import('@opentiny/vue-tabs')['default']
    ToolTabBar: typeof import('./src/components/ToolTabBar/index.vue')['default']
  }
}
